# PD Configuration.

cluster-id = 0

name = "pd"
data-dir = "default.pd"

host = "127.0.0.1"
client-port = 2379
advertise-client-port = 2379
peer-port = 2380
advertise-peer-port = 2380
port = 1234 # deprecate later
advertise-port = 1234 # deprecate later 
http-port = 9090 # deprecate later

initial-cluster = "pd=http://127.0.0.1:2380"
initial-cluster-state = "new"

root = "/pd" # deprecate later
lease = 3
log-level = "debug"
tso-save-interval = 2000
max-peer-count = 3


[balance]
min-capacity-used-ratio = 0.4
max-capacity-used-ratio = 0.9
max-leader-count = 10
max-sending-snap-count = 3
max-receiving-snap-count = 3
max-diff-score-fraction = 0.1
balance-interval = 30
max-balance-count = 16
max-balance-retry-per-loop = 10
max-balance-count-per-loop = 3
max-transfer-wait-count = 3
max-store-down-duration = 60


